Add missing includes
Fixes gcc warnings:
common/device.c: In function ‘device_script’:
common/device.c:63: warning: implicit declaration of function ‘cfg_foreach’
common/device.c:77: warning: implicit declaration of function ‘waitpid’